spring:
  datasource:
    url: jdbc:mysql://47.120.37.9:33060/sz_questionnaire?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&nullCatalogMeansCurrent=true
    password: lxl123456
    username: lxl
    