spring:
  datasource:
    url: jdbc:mysql://host:port/database?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&nullCatalogMeansCurrent=true
    password: yourpassword
    username: youusername
